# Generated by Django 3.0.5 on 2020-04-29 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
