# Generated by Django 3.0.5 on 2020-04-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_student_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='flag',
            new_name='key',
        ),
    ]
