# Generated by Django 3.0.5 on 2020-05-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0003_auto_20200429_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_features',
            field=models.BinaryField(),
        ),
    ]
