# Generated by Django 3.0.5 on 2020-05-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0004_auto_20200503_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='div',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
