# Generated by Django 3.0.5 on 2020-05-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0012_auto_20200507_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_feature',
            field=models.BinaryField(null=True),
        ),
    ]
