# Generated by Django 3.0.5 on 2020-05-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0013_auto_20200507_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
