# Generated by Django 3.0.5 on 2020-05-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0015_student_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='_10',
        ),
    ]
